Repository zilliztech/milvus-backup, pull requests merged in 2023-12, with the labels that each got.

#257 fix MinioChunkManager.Exist a exist path return false
  core/backup_impl_restore_backup.go
  core/storage/minio_chunk_manager.go
Labels: dco-passed, do-not-merge/missing-related-issue, size/S

#259 rename minio.cloudProvider to minio.storageType
  configs/backup.yaml
  core/paramtable/params.go
  core/storage/chunk_manager.go
  core/storage/minio_chunk_manager.go
  core/storage/options.go
Labels: dco-passed, size/M

#231 [test]Add test for array data type
  .github/workflows/main.yaml
  tests/base/client_base.py
  tests/base/collection_wrapper.py
  tests/common/common_func.py
  tests/common/common_type.py
  tests/requirements.txt
  tests/testcases/test_create_backup.py
  tests/testcases/test_get_backup.py
  tests/testcases/test_get_restore.py
  tests/testcases/test_list_backup.py
  tests/testcases/test_restore_backup.py
Labels: dco-passed, kind/improvement, size/L

#263 test: remove xfail for upsert testcase
  tests/testcases/test_create_backup.py
  tests/testcases/test_restore_backup.py
Labels: dco-passed, kind/improvement, size/XS

#262 flush all collection first
  core/backup_impl_create_backup.go
Labels: dco-passed, do-not-merge/missing-related-issue, size/M

#264 Update list backup rest api
  core/backup_meta.go
Labels: dco-passed, size/XS

#266 ci: use both master and release branch milvus image tag in ci
  .github/workflows/main.yaml
Labels: dco-passed, kind/improvement, size/XS

#272 update README.md
  README.md
Labels: ci-passed, dco-passed, size/XS

#274 fix restore not use backup index name
  core/milvus_sdk_wrapper.go
Labels: dco-passed, do-not-merge/missing-related-issue, size/XS

#275 Add advanced control paramters in create and restore cmd
  cmd/create.go
  cmd/restore.go
  core/backup_impl_create_backup.go
  core/backup_impl_restore_backup.go
  core/backup_server.go
  core/milvus_sdk_test.go
  core/milvus_sdk_wrapper.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: dco-passed, do-not-merge/missing-related-issue, size/XL
