Repository zilliztech/milvus-backup, pull requests merged in 2023-11, with the labels that each got.

#229 Optimize segment copy
  configs/backup.yaml
  core/backup_impl_create_backup.go
  core/backup_impl_restore_backup.go
  tests/base/client_base.py
Labels: dco-passed, lgtm, kind/improvement, size/L

#228 Update output of check command
  core/backup_context.go
Labels: dco-passed, lgtm, do-not-merge/missing-related-issue, size/XS

#232 [skip e2e]Increase timeout for nightly test
  .github/workflows/nightly.yaml
Labels: dco-passed, kind/improvement, size/XS

#230 Support Array datatype
  cmd/root.go
  core/backup_impl_create_backup.go
  core/backup_impl_restore_backup.go
  core/milvus_sdk_test.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
  go.mod
  go.sum
Labels: ci-passed, dco-passed, size/L

#233 Debug file copy
  configs/backup.yaml
  core/backup_impl_restore_backup.go
  core/paramtable/params.go
Labels: needs-dco, do-not-merge/missing-related-issue, size/S

#236 Fix backup slow
  core/backup_context.go
  core/backup_impl_create_backup.go
  core/paramtable/params.go
Labels: dco-passed, size/XS

#238 Add installation in README
  README.md
Labels: ci-passed, dco-passed, kind/improvement, size/S

#240 Modify docker file typo and fix milvus-backup path in ENTRYPOINT
  Dockerfile
Labels: dco-passed, size/XS

#246 Add LocalChunkManager support
  core/backup_context.go
  core/backup_context_test.go
  core/paramtable/params.go
  core/storage/azure_chunk_manager.go
  core/storage/chunk_manager.go
  core/storage/local_chunk_manager.go
  core/storage/minio_chunk_manager.go
  core/storage/types.go
Labels: dco-passed, size/L
