Repository zilliztech/milvus-backup, pull requests merged in 2023-10, with the labels that each got.

#214 Compatible to DescribeIndex error message update
  core/backup_impl_create_backup.go
Labels: ci-passed, dco-passed, do-not-merge/missing-related-issue, size/XS

#211 [ci]Optimization of ci runtime
  .github/workflows/main.yaml
  tests/testcases/test_restore_backup.py
Labels: dco-passed, kind/improvement, size/L

#208 [ci]Add nightly to run all test on master, 2.3 and 2.2 milvus version
  .github/workflows/nightly.yaml
Labels: dco-passed, kind/improvement, size/L

#218 Alert for port conflicts
  core/backup_server.go
Labels: dco-passed, size/XS

#220 Refine getbackup log
  core/backup_context.go
Labels: dco-passed, do-not-merge/missing-related-issue, size/S

#219 Support concurrent backup and restore
  cmd/create.go
  cmd/delete.go
  cmd/restore.go
  configs/backup.yaml
  core/backup_context.go
  core/backup_impl_create_backup.go
  core/backup_impl_restore_backup.go
  core/etcd_test.go
  core/milvus_sdk_wrapper.go
  core/milvus_source.go
  core/paramtable/params.go
  internal/common/workerpool.go
  internal/common/workerpool_test.go
  ut_test.go
Labels: dco-passed, size/XXL

#203 [test]Add more partitions in br test
  tests/base/client_base.py
  tests/testcases/test_restore_backup.py
Labels: ci-passed, dco-passed, kind/improvement, size/M

#223 Bump version to 0.4.1
  README.md
Labels: ci-passed, dco-passed, do-not-merge/missing-related-issue, size/XS

#222 [ci]Update perf test
  .github/workflows/main.yaml
  .github/workflows/nightly.yaml
  .github/workflows/perf.yaml
  tests/requirements.txt
  tests/testcases/test_backup_perf.py
Labels: dco-passed, kind/improvement, size/L

#225 fix default log level to info
  core/paramtable/base_table.go
  internal/log/log.go
Labels: dco-passed, do-not-merge/missing-related-issue, size/XS

#226 Support cross Azrue container backup
  configs/backup.yaml
  core/backup_impl_create_backup.go
  core/backup_impl_restore_backup.go
  core/paramtable/params.go
  core/storage/azure_chunk_manager.go
  core/storage/azure_object_storage.go
  core/storage/chunk_manager.go
  core/storage/options.go
  core/storage/types.go
Labels: needs-dco, size/L
