Repository zilliztech/milvus-backup, pull requests merged in 2023-09, with the labels that each got.

#191 Update version by goreleaser
  .goreleaser.yaml
  cmd/root.go
  cmd/version.go
  main.go
Labels: ci-passed, dco-passed, kind/improvement, size/M

#192 Add homebrew
  .github/workflows/release.yaml
  .goreleaser.yaml
Labels: dco-passed, kind/improvement, size/S

#194 Add check cmd
  cmd/check.go
  core/backup_context.go
  core/backup_server.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
Labels: ci-passed, dco-passed, kind/improvement, size/XL

#195 Add force backup option
  cmd/create.go
  core/backup_impl_create_backup.go
  core/backup_impl_restore_backup.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
Labels: ci-passed, dco-passed, kind/improvement, size/L

#198 [ci]Update image tag to 2.3.0-latest
  .github/workflows/main.yaml
  core/backup_context.go
  deployment/cluster/docker-compose.yml
  deployment/standalone/docker-compose.yml
Labels: ci-passed, dco-passed, kind/improvement, size/S

#200 [test]enable multi partitions in br test
  .github/workflows/main.yaml
  tests/base/client_base.py
  tests/testcases/test_restore_backup.py
Labels: ci-passed, dco-passed, kind/improvement, size/S

#202 Fix compatibility
  core/backup_impl_restore_backup.go
Labels: ci-passed, dco-passed, do-not-merge/missing-related-issue, size/XS

#196 Supports automatic generation of backup names
  core/backup_context_test.go
  core/backup_impl_create_backup.go
Labels: ci-passed, needs-dco, size/M

#206 Do some refine
  README.md
  cmd/get.go
  cmd/restore.go
  cmd/root.go
  configs/backup.yaml
  core/backup_context.go
  core/backup_context_test.go
  core/backup_impl_restore_backup.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
Labels: ci-passed, dco-passed, do-not-merge/missing-related-issue, size/L

#186 Support 2.3
  core/milvus_sdk_test.go
  example/prepare_data.py
  go.mod
  go.sum
Labels: ci-passed, dco-passed, kind/improvement, size/S

#207 [test]Add test cases to L0 to make sure checked in ci
  .github/workflows/main.yaml
  deployment/cluster/docker-compose.yml
  deployment/cluster/values.yaml
  deployment/standalone/docker-compose.yml
  deployment/standalone/values.yaml
  tests/testcases/test_restore_backup.py
Labels: ci-passed, dco-passed, kind/improvement, size/M
