Repository zilliztech/milvus-backup, pull requests merged in 2023-07, with the labels that each got.

#153 ci: add test for backup restore cross milvus version
  .github/workflows/main.yaml
Labels: ci-passed, dco-passed, kind/improvement, size/L

#154 ci: cancel previous runs in the PR when pushed new commits
  .github/workflows/main.yaml
Labels: ci-passed, dco-passed, kind/improvement, size/XS

#157 fix empty rootpath
  core/backup_impl_create_backup.go
Labels: ci-passed, dco-passed, size/XS

#159 Lazy initial milvus and storage client
  core/backup_context.go
  core/backup_impl_create_backup.go
  core/backup_impl_restore_backup.go
Labels: ci-passed, dco-passed, kind/improvement, size/L

#168 update example
  example/prepare_data.py
Labels: ci-passed, dco-passed, kind/improvement, size/XS

#164 Fix some bugs and add full_meta
  core/backup_context.go
  core/backup_context_test.go
  core/backup_impl_create_backup.go
  core/backup_impl_restore_backup.go
  core/backup_meta.go
  example/db_support/prepare_data.py
Labels: dco-passed, lgtm, size/L

#170 Make dbCollections parameter compatible to both string and json struct
  cmd/create.go
  cmd/restore.go
  core/backup_context_test.go
  core/backup_impl_create_backup.go
  core/backup_impl_restore_backup.go
  core/backup_server.go
  core/milvus_sdk_test.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
  core/utils/backup_request_util.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  example/delete_support/prepare_data.py
  go.mod
  go.sum
  proto_gen_go.sh
Labels: ci-passed, dco-passed, size/XL

#171 [test]update test case to support db
  tests/testcases/test_restore_backup.py
Labels: ci-passed, dco-passed, kind/improvement, size/M

#172 Fix compatibility to old backup without database info
  core/backup_context_test.go
  core/backup_impl_restore_backup.go
Labels: ci-passed, dco-passed, lgtm, size/S
