Repository zilliztech/milvus-backup, pull requests merged in 2023-06, with the labels that each got.

#136 Update milvus go sdk to support 2.2.9
  go.mod
  go.sum
Labels: dco-passed, lgtm, kind/improvement, size/S

#137 ci: add additional files to trigger CI when they are modified
  .github/workflows/main.yaml
Labels: ci-passed, dco-passed, kind/improvement, size/XS

#142 Fix bug when restore with collection name using CLI
  cmd/restore.go
Labels: ci-passed, dco-passed, lgtm, size/XS

#144 milvus backup support aliyun oss
  core/paramtable/params.go
  core/storage/aliyun/aliyun.go
  core/storage/minio_chunk_manager.go
  go.mod
  go.sum
Labels: ci-passed, dco-passed, do-not-merge/missing-related-issue, size/L

#147 Compatible with empty milvus rootPath
  core/backup_impl_create_backup.go
Labels: ci-passed, dco-passed, lgtm, size/M

#148 doc: add compatibility for milvus and milvus backup
  .goreleaser.yaml
  README.md
Labels: dco-passed, kind/improvement, size/XS

#149 Support cross bucket restore
  core/backup_impl_create_backup.go
  core/backup_impl_restore_backup.go
  core/backup_meta.go
  core/storage/minio_chunk_manager.go
Labels: ci-passed, dco-passed, size/M
