Repository zilliztech/milvus-backup, pull requests merged in 2023-08, with the labels that each got.

#177 [FIX]: Empty b.params.MinioCfg.RootPath handler (S3/Ceph)
  core/backup_impl_create_backup.go
Labels: ci-passed, dco-passed, lgtm, size/S

#180 Change some log level to avoid confusion
  core/backup_impl_create_backup.go
Labels: ci-passed, dco-passed, kind/improvement, size/S

#182 support loading minio and milvus config from env
  core/paramtable/base_table.go
Labels: ci-passed, dco-passed, do-not-merge/missing-related-issue, size/M

#187 Fix load config bug
  core/paramtable/base_table.go
Labels: ci-passed, dco-passed, lgtm, do-not-merge/missing-related-issue, size/M

#184 Support rename db,collection name when restore
  core/backup_impl_restore_backup.go
  core/backup_meta.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
  core/utils/convert_util.go
  core/utils/convert_util_test.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: ci-passed, dco-passed, lgtm, kind/improvement, size/L
