Repository zilliztech/milvus-backup, pull requests merged in 2023-04, with the labels that each got.

#121 Fix data duplicate when restore data larger than 10*maxSegmentGroupSize
  core/backup_context.go
Labels: ci-passed, dco-passed, lgtm, size/XS

#115 common: no longer reuse worker
  core/backup_context.go
  internal/common/workerpool.go
  internal/common/workerpool_test.go
Labels: ci-passed, dco-passed, lgtm, size/M

#123 feat: support absolute config file path
  core/paramtable/base_table.go
Labels: ci-passed, dco-passed, lgtm, size/XS

#127 ci: update issue template
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: dco-passed, kind/improvement, size/XS
