Repository zilliztech/milvus-backup, pull requests merged in 2024-12, with the labels that each got.

#472 backup & restore return error
  OWNERS
  core/backup_impl_create_backup.go
  core/backup_impl_restore_backup.go
  core/backup_meta_manager.go
  core/backup_server.go
Labels: needs-dco, do-not-merge/missing-related-issue, size/M, do-not-merge/invalid-owners-file

#482 use segment info after flush
  core/backup_impl_create_backup.go
Labels: dco-passed, size/M

#481 test: simplify test cases
  .github/mergify.yml
  .github/workflows/main.yaml
  .github/workflows/nightly.yaml
  .github/workflows/perf.yaml
  OWNERS
  build_image.sh
  deployment/cluster/values.yaml
  scripts/export_log_docker.sh
  scripts/get_image_tag_by_short_name.py
  tests/base/client_base.py
  tests/testcases/test_restore_backup.py
Labels: dco-passed, kind/improvement, size/L

#486 deployment: set minio console port to 9001
  deployment/standalone/docker-compose.yml
Labels: dco-passed, do-not-merge/missing-related-issue, size/XS

#455 test: add rbac backup restore check in ci
  .github/workflows/main.yaml
  deployment/standalone/rbac-values.yaml
  example/prepare_data.py
  example/prepare_rbac.py
  example/verify_data.py
  example/verify_rbac.py
Labels: dco-passed, lgtm, kind/improvement, size/XL

#488 restore: skip existing RBAC information during restoration
  core/backup_impl_restore_backup.go
Labels: dco-passed, do-not-merge/missing-related-issue, size/M

#490 server: fix nil pointer dereference
  core/backup_server.go
Labels: dco-passed, do-not-merge/missing-related-issue, size/XS
