Repository zilliztech/milvus-backup, pull requests merged in 2024-07, with the labels that each got.

#373 Update proto remove omitempty
  core/backup_meta.go
  core/backup_meta_manager.go
  core/proto/backuppb/backup.pb.go
  gen_proto.sh
  gen_swag.sh
  tests/api/milvus_backup.py
Labels: dco-passed, do-not-merge/missing-related-issue, size/M

#376 Refine Delete API
  core/backup_context.go
Labels: dco-passed, do-not-merge/missing-related-issue, size/XS

#382 Make it compatible for old milvus without database support
  core/backup_impl_create_backup.go
  example/index_support/prepare_data.py
Labels: needs-dco, do-not-merge/missing-related-issue, size/L

#380 Configurable server port
  cmd/server.go
Labels: dco-passed, do-not-merge/missing-related-issue, size/S

#383 fix: fix simple response possible NPE
  core/backup_impl_create_backup.go
  core/backup_meta.go
  core/backup_meta_manager.go
  core/backup_meta_test.go
Labels: dco-passed, do-not-merge/missing-related-issue, size/M
