Repository zilliztech/milvus-backup, pull requests merged in 2024-11, with the labels that each got.

#453 Update docs
  README.md
  docs/user_guide/api_demo.md
  docs/user_guide/e2e_demo_cli.md
  docs/user_guide/figs/log.png
Labels: size/L

#454 Update docs, add some FAQ
  README.md
  docs/user_guide/cross_storage.md
Labels: ci-passed, dco-passed, do-not-merge/missing-related-issue, size/M

#459 chore: lower log levels from info to debug
  core/backup_impl_create_backup.go
Labels: dco-passed, lgtm, size/XS

#457 fix rbac miss role bug
  go.mod
  go.sum
Labels: dco-passed, do-not-merge/missing-related-issue, size/XS

#469 Update README.md to add examples and configurations table.
  README.md
Labels: ci-passed, dco-passed, do-not-merge/missing-related-issue, size/M

#458 ci: add arm image publish
  .github/workflows/release.yaml
Labels: dco-passed, kind/improvement, size/M
