Repository zilliztech/milvus-backup, pull requests merged in 2024-09, with the labels that each got.

#417 BugFix: fix crossStorage load issue
  core/paramtable/params.go
Labels: needs-dco, do-not-merge/missing-related-issue, size/XS

#420 Command-line parameters for backup MinIO cross-storage
  core/backup_context.go
  core/backup_server.go
  core/paramtable/base_table.go
  core/paramtable/params.go
Labels: dco-passed, do-not-merge/missing-related-issue, size/M

#422 fix cross restore path
  core/backup_impl_restore_backup.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: dco-passed, size/S

#425 ci: update actions/upload-artifact version
  .github/workflows/main.yaml
  .github/workflows/nightly.yaml
  .github/workflows/perf.yaml
Labels: dco-passed, kind/improvement, size/XS

#424 fix getBackup panic if pass a invalid backup ID
  core/backup_context.go
Labels: dco-passed, do-not-merge/missing-related-issue, size/S

#428 enhance: support maxShardNum parameter in restore request
  core/backup_impl_create_backup.go
  core/backup_impl_restore_backup.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: dco-passed, do-not-merge/missing-related-issue, size/XL

#431 test: add test cases for text match feature
  tests/requirements.txt
  tests/testcases/test_restore_backup.py
Labels: dco-passed, kind/improvement, size/S
