Repository zilliztech/milvus-backup, pull requests merged in 2024-01, with the labels that each got.

#279 update minio_chunk_manager Read
  core/storage/minio_chunk_manager.go
Labels: needs-dco, size/M

#281 Refine proto and swag
  build.sh
  core/backup_server.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  gen_proto.sh
  gen_swag.sh
Labels: dco-passed, do-not-merge/missing-related-issue, size/L

#284 Add retry in backup prepare & Fix backup size lost bug
  core/backup_impl_create_backup.go
  core/backup_meta.go
Labels: dco-passed, do-not-merge/missing-related-issue, size/M

#286 fix size lost
  core/proto/backuppb/backup.pb.go
Labels: dco-passed, do-not-merge/missing-related-issue, size/S

#287 test: add testcase for multi vec
  .github/mergify.yml
  .github/workflows/main.yaml
  tests/common/common_type.py
  tests/requirements.txt
  tests/testcases/test_restore_backup.py
Labels: dco-passed, kind/improvement, size/L
