Repository zilliztech/milvus-backup, pull requests merged in 2024-08, with the labels that each got.

#388 ci: update test env
  .github/workflows/main.yaml
  .github/workflows/nightly.yaml
  .github/workflows/perf.yaml
  tests/base/client_base.py
  tests/requirements.txt
  tests/testcases/test_restore_backup.py
Labels: dco-passed, kind/improvement, size/M

#392 Refine scripts build with version
  build.sh
  build_image.sh
  go.mod
  go.sum
  scripts/gen_proto.sh
  scripts/gen_swag.sh
Labels: dco-passed, do-not-merge/missing-related-issue, size/M

#394 Support skipImportDiskQuotaCheck option in restore
  core/backup_impl_restore_backup.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.mod
  go.sum
Labels: dco-passed, do-not-merge/missing-related-issue, size/L

#397 Add Makefile
  Makefile
Labels: dco-passed, do-not-merge/missing-related-issue, size/S

#396 Remove useless method in chunkManager interface
  core/storage/types.go
Labels: dco-passed, do-not-merge/missing-related-issue, size/S

#400 fix: repair delete case
  core/backup_impl_restore_backup.go
Labels: dco-passed, do-not-merge/missing-related-issue, size/S

#401 Fix: mkdir before copying file for local chunk manager
  core/storage/local_chunk_manager.go
Labels: dco-passed, size/S

#403 upgrade milvus-go-sdk to v2.4.2-0.20240821030256-0c339b63d265
  go.mod
  go.sum
Labels: dco-passed, do-not-merge/missing-related-issue, size/S

#402 chore: Update Dockerfile to install ca-certificates
  Dockerfile
Labels: dco-passed, kind/improvement, size/XS

#405 Support backup&restore RBAC
  cmd/create.go
  cmd/restore.go
  core/backup_context.go
  core/backup_impl_create_backup.go
  core/backup_impl_restore_backup.go
  core/backup_meta_manager.go
  core/milvus_sdk_wrapper.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: dco-passed, size/XXL

#398 Support cross storage backup/restore
  Makefile
  configs/backup.yaml
  core/backup_context.go
  core/backup_context_test.go
  core/backup_impl_create_backup.go
  core/backup_impl_restore_backup.go
  core/milvus_storage_test.go
  core/paramtable/params.go
  core/storage/azure_chunk_manager.go
  core/storage/azure_object_storage.go
  core/storage/chunk_manager.go
  core/storage/copier.go
  core/storage/local_chunk_manager.go
  core/storage/minio_chunk_manager.go
  core/storage/options.go
  core/storage/types.go
  scripts/gen_swag.sh
Labels: dco-passed, size/XXL

#407 Refine cross storage backup and add doc
  configs/backup.yaml
  core/backup_context.go
  core/backup_impl_create_backup.go
  core/backup_impl_restore_backup.go
  core/paramtable/params.go
  core/storage/copier.go
  docs/cross_storage_backup_restore.md
Labels: dco-passed, size/L

#410 update readme
  README.md
Labels: ci-passed, dco-passed, kind/improvement, size/XS
