Repository zilliztech/milvus-backup, pull requests merged in 2024-05, with the labels that each got.

#209 Prints the current backup config file in yaml format to stdio
  cmd/backup_yaml.go
  cmd/root.go
  core/paramtable/base_table_test.go
  go.mod
Labels: needs-dco, kind/improvement, size/L

#333 Update Dockerfile
  Dockerfile
Labels: needs-dco, do-not-merge/missing-related-issue, size/XS

#330 Update sdk to support f16/bf16
  core/backup_impl_create_backup.go
  core/backup_impl_restore_backup.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.mod
  go.sum
Labels: dco-passed, do-not-merge/missing-related-issue, size/XL

#339 Refine GC error log
  core/backup_impl_create_backup.go
Labels: dco-passed, do-not-merge/missing-related-issue, size/S

#341 enhance: Support segment level restore concurrency
  core/backup_impl_create_backup.go
  core/backup_impl_restore_backup.go
  internal/common/workerpool.go
Labels: dco-passed, do-not-merge/missing-related-issue, size/L

#340 feat: Support CDC
  core/backup_impl_create_backup.go
  core/backup_meta.go
  core/milvus_sdk_wrapper.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
  core/utils/convert_util.go
  go.mod
  go.sum
Labels: dco-passed, do-not-merge/missing-related-issue, size/XL

#324 ci: update image tag for cross version br
  .github/workflows/main.yaml
Labels: dco-passed, kind/improvement, size/XS

#342 test: add xfail for restore case with delete
  tests/testcases/test_restore_backup.py
Labels: dco-passed, kind/improvement, size/XS

#336 Update Dockerfile
  Dockerfile
Labels: needs-dco, do-not-merge/missing-related-issue, size/XS

#344 Update simpleResponse to support CDC
  core/backup_meta.go
Labels: dco-passed, do-not-merge/missing-related-issue, size/S

#343 ci: verify backup and restore after upgrading
  .github/workflows/main.yaml
Labels: dco-passed, kind/improvement, size/M

#345 test: refactor http client for test
  tests/api/milvus_backup.py
  tests/requirements.txt
  tests/testcases/test_delete_backup.py
Labels: dco-passed, kind/improvement, size/L

#346 test: add sparse vector datatype
  tests/common/common_func.py
  tests/common/common_type.py
  tests/requirements.txt
  tests/testcases/test_restore_backup.py
Labels: dco-passed, kind/improvement, size/M

#327 test: add pk diff check
  tests/base/client_base.py
  tests/testcases/test_restore_backup.py
Labels: dco-passed, kind/improvement, size/XS

#338 test: add more json datatype in br test cases
  tests/testcases/test_restore_backup.py
Labels: dco-passed, kind/improvement, size/M

#315 ci: add 2.4 release to ci
  .github/workflows/main.yaml
Labels: dco-passed, do-not-merge/missing-related-issue, size/XS

#349 Define meta v2
  core/backup_context.go
  core/backup_impl_create_backup.go
  core/backup_impl_restore_backup.go
  core/backup_meta.go
  core/backup_meta_manager.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
  core/storage/minio_chunk_manager.go
Labels: needs-dco, size/XXL

#352 ci: refine image building
  .github/workflows/main.yaml
  .github/workflows/release.yaml
  .goreleaser.yaml
  Dockerfile
  build/deployment/docker-compose.yaml
  build_image.sh
Labels: dco-passed, kind/improvement, size/M

#288 test: add float16 and brain float16 datatype for br
  tests/common/common_func.py
  tests/requirements.txt
  tests/testcases/test_restore_backup.py
Labels: dco-passed, kind/improvement, size/L

#354 enhance: Support restore progress
  core/backup_context.go
  core/backup_impl_restore_backup.go
  core/backup_meta.go
  core/backup_meta_manager.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
Labels: dco-passed, size/XL

#348 Fix enabling both drop_exist_collection and skip_create_collection
  cmd/restore.go
  core/backup_impl_restore_backup.go
Labels: dco-passed, do-not-merge/missing-related-issue, size/S
