Repository zilliztech/milvus-backup, pull requests merged in 2024-06, with the labels that each got.

#356 Optimize restore speed with many small segments
  core/backup_context.go
  core/backup_impl_create_backup.go
  core/backup_meta_manager.go
Labels: dco-passed, size/L

#357 Support restore L0 segments
  core/backup_context.go
  core/backup_impl_create_backup.go
  core/backup_impl_restore_backup.go
  core/backup_meta.go
  core/backup_meta_manager.go
  core/milvus_sdk_wrapper.go
  core/paramtable/base_table.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
  example/delete_support/prepare_data.py
  example/delete_support/verify_data.py
  go.mod
  go.sum
  internal/common/common.go
  internal/kv/kv.go
  internal/util/typeutil/convension.go
  internal/util/typeutil/set.go
  internal/util/typeutil/string_util.go
  internal/util/typeutil/time.go
  internal/util/typeutil/type.go
Labels: needs-dco, size/XXL

#358 test: enable cases related to delete
  .github/workflows/release.yaml
  tests/testcases/test_restore_backup.py
Labels: dco-passed, kind/improvement, size/XS

#362 ci: update goreleaser config
  .github/workflows/release.yaml
  .goreleaser.yaml
Labels: dco-passed, do-not-merge/missing-related-issue, size/XS

#365 Update swagger UI
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: dco-passed, do-not-merge/missing-related-issue, size/M

#368 test: add case to check ts order after restore
  tests/testcases/test_restore_backup.py
Labels: dco-passed, kind/improvement, size/M

#370 Support backup progress
  core/backup_context.go
  core/backup_impl_create_backup.go
  core/backup_meta.go
  core/backup_meta_manager.go
Labels: dco-passed, size/M
