Repository zilliztech/milvus-backup, pull requests merged in 2025-05, with the labels that each got.

#631 ci: use custom config for deployment
  deployment/standalone/custom_config.yaml
  deployment/standalone/docker-compose.yml
  example/prepare_data.py
  tests/common/common_func.py
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/M

#646 backup, restore: use base64 to encode default value proto
  core/backup/collection.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
  core/restore/collection.go
  core/restore/collection_test.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XL

#645 fix: update golang.org/x/oauth2 to address CVE-2025-22868
  go.mod
  go.sum
Labels: ci-passed, dco-passed, lgtm, approved, size/XS

#648 backup: sort by field id
  core/backup/collection_test.go
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XS

#644 client: add identifier to outgoing ctx
  core/client/grpc.go
  core/client/grpc_test.go
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/S

#649 restore: fix skip rbac not work
  core/restore/task.go
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XS

#650 *: update dep
  .github/workflows/main.yaml
  .github/workflows/nightly.yaml
  .github/workflows/perf.yaml
  .github/workflows/release.yaml
  Dockerfile
  core/storage/aliyun/aliyun.go
  core/storage/tencent/tencent.go
  go.mod
  go.sum
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XL

#651 storage: remove list object operation from copy function
  .mockery.yaml
  core/mocks/chunkManager_mock.go
  core/mocks/grpc_mock.go
  core/storage/azure_chunk_manager.go
  core/storage/chunk_manager.go
  core/storage/copier.go
  core/storage/gcp_native_chunk_manager.go
  core/storage/local_chunk_manager.go
  core/storage/minio_chunk_manager.go
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#653 cmd: return 1 when fail
  .gitignore
  cmd/check.go
  cmd/check/backup_yaml.go
  cmd/check/check.go
  cmd/cmd.go
  cmd/create.go
  cmd/create/create.go
  cmd/del/delete.go
  cmd/delete.go
  cmd/get.go
  cmd/get/get.go
  cmd/helpers.go
  cmd/list.go
  cmd/list/list.go
  cmd/restore.go
  cmd/restore/restore.go
  cmd/root.go
  cmd/root/root.go
  cmd/server.go
  cmd/server/server.go
  core/backup/task.go
  go.mod
  main.go
  version/version.go
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#654 storage: skip empty file when copy
  core/storage/copier.go
Labels: ci-passed, dco-passed, approved, kind/improvement, size/S

#657 *: fix restore progress tracking
  .mockery.yaml
  cmd/cmd.go
  core/backup_context.go
  core/backup_impl_restore_backup.go
  core/backup_server.go
  core/meta/backup_meta.go
  core/meta/backup_meta_manager.go
  core/meta/taskmgr/mgr.go
  core/meta/taskmgr/restore.go
  core/meta/taskmgr/restore_test.go
  core/mocks/restoreCollTaskView_mock.go
  core/mocks/restoreTaskView_mock.go
  core/pbconv/pbconv.go
  core/pbconv/pbconv_test.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
  core/restore/collection.go
  core/restore/task.go
  core/task.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#658 cmd: export v2 restore flag
  cmd/restore/restore.go
  cmd/restore/restore_test.go
  docs/user_guide/figs/mul_seg_restore.png
  docs/user_guide/mul_seg_restore.md
  go.mod
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#660 taskmgr: add read lock
  core/meta/taskmgr/restore.go
  core/meta/taskmgr/restore_test.go
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/L

#665 restore, client: improve retry logic
  core/client/grpc.go
  core/restore/collection.go
Labels: ci-passed, dco-passed, approved, kind/improvement, size/M

#667 backup: improve rpc backup error msg
  core/backup/task.go
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XS
