Repository zilliztech/milvus-backup, pull requests merged in 2025-07, with the labels that each got.

#716 milvus: retry on Bulkinsert task status fetch failure
  core/client/milvus/grpc.go
  core/client/milvus/restful.go
Labels: dco-passed, approved, kind/improvement, size/M

#724 cloud: hiding confidential information in logs
  core/client/cloud/api.go
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XS

#727 storage: use azureAccountName directly in URL instead of accessKeyID
  core/storage/azure.go
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XS

#718 *: support auto-renewal of GC pause during backup
  .mockery.yaml
  configs/backup.yaml
  core/backup/gc_controller.go
  core/backup/gc_controller_test.go
  core/backup/task.go
  core/backup_impl_create_backup.go
  core/client/milvus/grpc_mock.go
  core/client/milvus/manage_mock.go
  core/paramtable/params.go
  core/proto/backup.proto
  core/storage/client_mock.go
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#730 milvus: skip retry if server not support get segment info
  core/client/milvus/restful.go
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/M

#733 restore, paramtable: parallelize BulkImport tasks
  configs/backup.yaml
  core/paramtable/params.go
  core/restore/collection.go
  core/restore/task.go
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#734 *: support int8 vector
  core/client/milvus/grpc_test.go
  core/client/milvus/restful.go
  core/meta/backup_meta.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
  core/restore/collection.go
  core/restore/planner.go
  core/storage/copy_task.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XXL

#736 *: remove unused code
  core/backup/collection.go
  core/backup/collection_test.go
  core/backup/database.go
  core/backup/database_test.go
  core/backup/task.go
  core/backup_context.go
  core/backup_impl_create_backup.go
  core/backup_impl_restore_backup.go
  core/client/milvus/grpc.go
  core/client/milvus/restful.go
  core/meta/taskmgr/restore.go
  core/meta/taskmgr/restoreCollTaskView_mock.go
  core/meta/taskmgr/restoreTaskView_mock.go
  core/meta/taskmgr/restore_test.go
  core/paramtable/base_table.go
  core/proto/backuppb/backup.pb.go
  core/restore/collMapper_mock.go
  core/restore/collection.go
  core/restore/planner.go
  core/restore/planner_test.go
  core/restore/task.go
  core/storage/copier.go
  core/storage/gcp_native.go
  core/storage/minio.go
  core/task.go
  core/utils/convert_util.go
  core/utils/convert_util_test.go
  core/utils/uuid.go
  core/utils/version_util.go
  core/utils/version_util_test.go
  internal/aimd/limiter.go
  internal/aimd/limiter_test.go
  internal/namespace/namespace.go
  internal/namespace/namespace_test.go
  internal/pbconv/pbconv.go
  internal/pbconv/pbconv_test.go
  internal/retry/options.go
  internal/retry/retry.go
  internal/retry/retry_test.go
  internal/util/errorutil/util.go
  internal/util/errorutil/util_test.go
  internal/util/logutil/logutil.go
  internal/util/retry/retry_test.go
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XL

#737 readme: add compatibility and v2 restore mode
  README.md
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/S

#738 readme: recommend using latest milvus-backup release in README
  README.md
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XS

#740 *: fix log params
  cmd/check/backup_yaml.go
  cmd/check/check.go
  cmd/create/create.go
  cmd/del/delete.go
  cmd/get/get.go
  cmd/list/list.go
  cmd/migrate/migrate.go
  cmd/restore/restore.go
  cmd/root/root.go
  cmd/server/server.go
  core/meta/taskmgr/restoreCollTaskView_mock.go
  core/meta/taskmgr/restoreTaskView_mock.go
  core/paramtable/base_table.go
  core/paramtable/params.go
  core/proto/backuppb/backup.pb.go
  core/restore/collMapper_mock.go
  internal/log/global.go
  internal/log/log.go
Labels: dco-passed, lgtm, approved, kind/improvement, size/L

#732 test: enable storage v2 for backup&restore
  .github/workflows/main.yaml
  example/prepare_data.py
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/L

#743 Create env_variables.md
  docs/user_guide/env_variables.md
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/M
