Repository zilliztech/milvus-backup, pull requests merged in 2025-09, with the labels that each got.

#764 cmd/restore: rename restore_index to rebuild_index
  cmd/restore/restore.go
  core/backup/collection.go
Labels: ci-passed, dco-passed, lgtm, approved, size/S

#769 *: make golangci-lint happy
  cmd/restore/restore.go
  core/restore/task.go
  core/server/restore.go
  core/storage/azure.go
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/S

#773 test: use sentence-transformers/all-MiniLM-L6-v2 model for ci
  deployment/standalone/docker-compose-tei.yml
  tests/testcases/test_restore_backup.py
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XS

#780 storage: return file info directly when prefix is a file
  core/storage/local.go
  core/storage/local_test.go
Labels: ci-passed, dco-passed, lgtm, approved, size/M

#783 fix(log): correct file logging config
  cmd/restore/restore_test.go
  core/paramtable/params.go
  internal/log/log.go
Labels: ci-passed, dco-passed, lgtm, approved, size/M

#787 *: support read backup root path from request
  cmd/restore/restore.go
  core/backup/collection.go
  core/backup/database.go
  core/backup/gc_controller.go
  core/backup/gc_controller_test.go
  core/backup/rbac.go
  core/backup/rpc_channel_pos.go
  core/backup/task.go
  core/backup/task_test.go
  core/backup_context.go
  core/backup_impl_create_backup.go
  core/meta/backup_meta.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XXL

#796 ci: remove pull_request trigger from azure workflow to avoid secrets access issues
  .github/workflows/azure.yaml
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XS

#798 meta, backup: add task id to meta map
  core/backup/collection.go
  core/backup/database_test.go
  core/backup/task_test.go
  core/backup_impl_create_backup.go
  core/meta/backup_meta_manager.go
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/L
