Repository zilliztech/milvus-backup, pull requests merged in 2025-01, with the labels that each got.

#497 Remove all leading slashes from minio rootPath
  core/paramtable/params.go
Labels: dco-passed, lgtm, size/XS

#498 fix owner filter
  OWNERS
Labels: dco-passed, do-not-merge/missing-related-issue, size/XS

#499 add job name and fix mergify ci-passed rule
  .github/mergify.yml
  .github/workflows/main.yaml
Labels: dco-passed, approved, size/S

#494 TLS Authentication in Backup Tool
  README.md
  cmd/backup_yaml.go
  configs/backup.yaml
  core/backup_context.go
  core/paramtable/base_table.go
  core/paramtable/params.go
Labels: dco-passed, lgtm, approved, size/M

#501 add default value for tls cert path and server name
  core/paramtable/params.go
Labels: dco-passed, approved, do-not-merge/missing-related-issue, size/S

#502 fix conditions in mergify.yml
  .github/mergify.yml
Labels: ci-passed, dco-passed, approved, kind/improvement, size/S

#492 feat: support Milvus 2.5 function feature by bypassing SDK
  .github/workflows/main.yaml
  .github/workflows/nightly.yaml
  .github/workflows/perf.yaml
  .github/workflows/release.yaml
  Dockerfile
  Makefile
  cmd/backup_yaml.go
  cmd/check.go
  cmd/create.go
  cmd/delete.go
  cmd/get.go
  cmd/list.go
  cmd/restore.go
  cmd/root.go
  cmd/server.go
  core/backup_context.go
  core/backup_context_test.go
  core/backup_impl_create_backup.go
  core/backup_impl_restore_backup.go
  core/backup_meta_test.go
  core/backup_server.go
  core/backup_server_test.go
  core/client/cfg.go
  core/client/grpc.go
  core/client/restful.go
  core/meta/backup_meta.go
  core/meta/backup_meta_manager.go
  core/milvus_sdk_test.go
  core/milvus_sdk_wrapper.go
  core/milvus_storage_test.go
  core/paramtable/base_table_test.go
  core/pbconv/bak_to_milvus.go
  core/pbconv/bak_to_milvus_test.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
  core/restore/collection.go
  core/restore/collection_test.go
  core/storage/chunk_manager.go
  core/storage/local_chunk_manager.go
  core/storage/mpath/path.go
  core/storage/mpath/path_test.go
  core/utils/backup_request_util.go
  core/utils/convert_util.go
  core/utils/version_util.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.mod
  go.sum
  internal/common/workerpool.go
  internal/util/errorutil/util_test.go
  internal/util/grpcclient/client.go
  main.go
  version/version.go
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#447 test: add testcases for bm25 function
  tests/requirements.txt
  tests/testcases/test_restore_backup.py
  tests/utils/util_common.py
  tests/utils/util_pymilvus.py
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/L

#503 use restful api to create bulk inert job
  Makefile
  core/backup_context.go
  core/backup_impl_restore_backup.go
  core/client/grpc.go
  core/client/restful.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
  core/restore/collection.go
  core/storage/mpath/path.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XL

#506 test: add restore v2 test case
  tests/testcases/test_restore_backup.py
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XS

#511 *: set skip_disk_quota_check parameter to true permanently
  core/backup_impl_restore_backup.go
  core/client/grpc.go
  core/client/restful.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
  core/restore/collection.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: ci-passed, dco-passed, lgtm, approved, size/XL

#509 add unit test and remove unused code
  .github/mergify.yml
  .github/workflows/main.yaml
  Makefile
  README.md
  core/backup_context.go
  core/backup_context_test.go
  core/backup_meta_test.go
  core/backup_server_test.go
  core/client/cfg.go
  core/client/cfg_test.go
  core/client/grpc.go
  core/client/grpc_test.go
  core/client/restful.go
  core/paramtable/base_table_test.go
  core/paramtable/params_test.go
  core/proto/backuppb/backup.pb.go
  core/restore/collection.go
  internal/common/error.go
  internal/common/tuple.go
  internal/util/funcutil/func.go
  internal/util/funcutil/random.go
  internal/util/grpcclient/client.go
  internal/util/grpcclient/errors.go
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XXL

#512 restore: fix restore index bug in type check
  core/restore/collection.go
  go.mod
Labels: dco-passed, approved, size/M

#516 restore/rbac: skip exited grant
  core/backup_impl_restore_backup.go
  core/restore/rbac.go
  core/restore/rbac_test.go
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#518 owners: add an approver and reviewer
  OWNERS
Labels: dco-passed, approved, do-not-merge/missing-related-issue, size/XS

#517 restore/collection: retry when call create collection fail
  core/restore/collection.go
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XS

#520 mergify: edit condition to fit 2.5
  .github/mergify.yml
Labels: ci-passed, dco-passed, approved, kind/improvement, size/M

#523 core, cmd: fix typo
  cmd/backup_yaml.go
  core/paramtable/base_table.go
Labels: ci-passed, dco-passed, approved, kind/improvement, size/XS
