Repository zilliztech/milvus-backup, pull requests merged in 2025-02, with the labels that each got.

#526 restore: use partition num in backup if partition key was set
  core/client/grpc.go
  core/restore/collection.go
Labels: ci-passed, dco-passed, approved, do-not-merge/missing-related-issue, size/M

#528 restore: improve log format
  core/restore/collection.go
Labels: ci-passed, dco-passed, approved, kind/improvement, size/XS

#525 common, client: add aimd rate limiter for some rpc
  core/client/grpc.go
  core/client/grpc_test.go
  internal/common/aimd_limiter.go
  internal/common/aimd_limiter_test.go
Labels: ci-passed, dco-passed, approved, kind/improvement, size/L

#530 .github: add depbot
  .github/dependabot.yml
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/S

#535 .github: add kind/improvement tag for dependabot's PR
  .github/mergify.yml
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/S

#542 common: improve aimd limiter
  core/client/grpc.go
  internal/common/aimd_limiter.go
Labels: ci-passed, dco-passed, approved, kind/improvement, size/S

#544 client, restore: use end_ts as key instead of end_time
  core/client/grpc.go
  core/client/restful.go
  core/restore/collection.go
Labels: dco-passed, approved, size/S

#545 test: fix nightly github action
  .github/workflows/nightly.yaml
  scripts/get_latest_tag.py
Labels: dco-passed, lgtm, approved, kind/improvement, size/M

#553 *: use path.join instead of manually concatenating paths
  core/backup_impl_restore_backup.go
  core/restore/collection.go
  core/storage/copier.go
Labels: ci-passed, dco-passed, lgtm, approved, size/M

#554 meta: set progress to 0 when total size is 0
  core/meta/backup_meta_manager.go
Labels: ci-passed, dco-passed, lgtm, approved, size/XS

#555 *: improve build workflow
  .github/workflows/release.yaml
  .goreleaser.yaml
  Dockerfile
  Makefile
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/S
