Repository zilliztech/milvus-backup, pull requests merged in 2025-04, with the labels that each got.

#608 fix: Fix the bug that unable to restore json path index
  core/restore/collection.go
Labels: ci-passed, dco-passed, lgtm, approved, size/M

#615 test: add rbac restore testcases
  .github/workflows/main.yaml
  .github/workflows/nightly.yaml
  .gitignore
  deployment/standalone/docker-compose-rbac.yml
  deployment/standalone/user.yaml
  tests/base/client_base.py
  tests/common/common_type.py
  tests/conftest.py
  tests/pytest.ini
  tests/testcases/test_restore_backup_with_rbac.py
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/L

#619 ci: fix get latest tag
  scripts/get_image_tag_by_short_name.py
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/M

#618 contributing.md: add
  .github/mergify.yml
  CONTRIBUTING.md
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/L

#620 test: add dynamic data for insert
  tests/testcases/test_restore_backup.py
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/S

#621 backup: print logs when reading rbac info done
  core/backup/rbac.go
Labels: dco-passed, approved, kind/improvement, size/XS

#610 test: enable backup test cases for json path index after code fix
  tests/base/client_base.py
  tests/requirements.txt
  tests/testcases/test_restore_backup.py
Labels: ci-passed, dco-passed, lgtm, approved, size/M

#609 *: read binlog file list from proxy node
  configs/backup.yaml
  core/backup/collection.go
  core/backup/collection_test.go
  core/backup/database.go
  core/backup/rpc_channel_pos.go
  core/backup/task.go
  core/backup_context.go
  core/backup_impl_create_backup.go
  core/backup_impl_restore_backup.go
  core/client/grpc.go
  core/client/manage.go
  core/client/restful.go
  core/meta/backup_meta.go
  core/meta/backup_meta_manager.go
  core/mocks/grpc_mock.go
  core/namespace/namespace.go
  core/namespace/namespace_test.go
  core/paramtable/base_table.go
  core/paramtable/params.go
  core/pbconv/bak_to_milvus.go
  core/pbconv/pbconv.go
  core/pbconv/pbconv_test.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
  core/restore/collection.go
  core/restore/collection_test.go
  core/restore/database.go
  core/restore/ns_renamer.go
  core/restore/task.go
  core/restore/task_test.go
  core/storage/copier.go
  core/storage/minio_chunk_manager.go
  core/storage/mpath/path.go
  core/storage/mpath/path_test.go
  core/storage/types.go
  core/utils/backup_request_util.go
  core/utils/convert_util.go
  core/utils/convert_util_test.go
  core/utils/request_util.go
  deployment/standalone/docker-compose.yml
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.mod
  go.sum
  internal/common/workerpool.go
  internal/common/workerpool_test.go
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#624 restore: compatible db backup is empty
  core/restore/task.go
  core/restore/task_test.go
Labels: dco-passed, lgtm, approved, do-not-merge/missing-related-issue, size/M

#496 milvus-backup failure for Azure Blob Storage Account
  core/storage/azure_object_storage.go
Labels: ci-passed, dco-passed, lgtm, approved, size/M

#625 gcpnative support for backup tool (GCS implemented using Google Cloud Storage libraries)
  README.md
  cmd/backup_yaml.go
  configs/backup.yaml
  core/backup_context.go
  core/paramtable/base_table.go
  core/paramtable/params.go
  core/storage/chunk_manager.go
  core/storage/gcp_native_chunk_manager.go
  core/storage/options.go
  go.mod
  go.sum
Labels: ci-passed, dco-passed, lgtm, approved, size/XL

#627 restore: filter backup after rename
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
  core/restore/task.go
  core/restore/task_test.go
  core/storage/azure_object_storage.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XXL

#630 backup: fix backup binlog not append
  .mockery.yaml
  core/backup/collection.go
  core/backup/collection_test.go
  core/backup/task.go
  core/mocks/chunkManager_mock.go
  core/proto/backuppb/backup.pb.go
  core/restore/task.go
  core/storage/gcp_native_chunk_manager.go
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XL

#632 mpath: allow empty root dir
  core/storage/mpath/path.go
  core/storage/mpath/path_test.go
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/M

#634 *: add some ut
  Makefile
  core/backup/collection_test.go
  core/client/restful.go
  core/namespace/namespace.go
  core/namespace/namespace_test.go
  core/restore/collection.go
  core/restore/ns_renamer_test.go
  deployment/standalone/docker-compose.yml
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/L

#636 backup: verify binlog number when run backup
  core/backup/collection.go
  core/backup/collection_test.go
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/M
