Repository zilliztech/milvus-backup, pull requests merged in 2025-06, with the labels that each got.

#673 *: refine storage pkg
  .mockery.yaml
  core/backup/collection.go
  core/backup/collection_test.go
  core/backup/task.go
  core/backup_context.go
  core/backup_impl_create_backup.go
  core/client/grpc_mock.go
  core/meta/taskmgr/restoreCollTaskView_mock.go
  core/meta/taskmgr/restoreTaskView_mock.go
  core/mocks/chunkManager_mock.go
  core/paramtable/params.go
  core/pbconv/pbconv_test.go
  core/restore/collection.go
  core/restore/task.go
  core/restore/task_test.go
  core/storage/aliyun.go
  core/storage/aliyun/aliyun.go
  core/storage/azure.go
  core/storage/azure_chunk_manager.go
  core/storage/azure_object_storage.go
  core/storage/chunk_manager.go
  core/storage/client.go
  core/storage/client_mock.go
  core/storage/copier.go
  core/storage/copy_task.go
  core/storage/funcs.go
  core/storage/funcs_test.go
  core/storage/gcp.go
  core/storage/gcp/gcp.go
  core/storage/gcp_native.go
  core/storage/gcp_native_chunk_manager.go
  core/storage/local.go
  core/storage/local_chunk_manager.go
  core/storage/local_test.go
  core/storage/minio.go
  core/storage/minio_chunk_manager.go
  core/storage/object_iterator_mock.go
  core/storage/options.go
  core/storage/tencent.go
  core/storage/tencent/tencent.go
  core/storage/types.go
  go.mod
  internal/common/workerpool.go
  internal/common/workerpool_test.go
Labels: ci-passed, dco-passed, approved, kind/improvement, size/XXL

#683 *: remove some unnecessary dependencies
  core/storage/tencent.go
  core/utils/id_generator.go
  core/utils/id_generator_test.go
  go.mod
  go.sum
  internal/util/retry/retry_test.go
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/M

#681 ci: add 2.2 and 2.3 as source tag for cross version br
  .github/mergify.yml
  .github/workflows/main.yaml
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XS

#688 backup, client: check feature before backup
  core/backup/database.go
  core/backup/database_test.go
  core/backup/task.go
  core/client/grpc.go
  core/client/grpc_mock.go
  core/client/grpc_test.go
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#690 *: support migrate to zilliz
  cmd/cmd.go
  cmd/migrate/migrate.go
  cmd/migrate/migrate_test.go
  configs/backup.yaml
  core/backup/collection.go
  core/backup/collection_test.go
  core/backup/database.go
  core/backup/database_test.go
  core/backup/rbac.go
  core/backup/rpc_channel_pos.go
  core/backup/task.go
  core/backup_context.go
  core/client/cloud/api.go
  core/client/cloud/api_test.go
  core/client/milvus/grpc.go
  core/client/milvus/grpc_mock.go
  core/client/milvus/grpc_test.go
  core/client/milvus/manage.go
  core/client/milvus/restful.go
  core/client/milvus/restful_test.go
  core/meta/meta.go
  core/meta/meta_test.go
  core/meta/taskmgr/mgr.go
  core/meta/taskmgr/migrate.go
  core/migrate/task.go
  core/paramtable/params.go
  core/restore/collection.go
  core/restore/database.go
  core/restore/rbac.go
  core/restore/task.go
  core/restore/task_test.go
  core/storage/aliyun.go
  core/storage/azure.go
  core/storage/client.go
  core/storage/copy_task.go
  core/storage/factory.go
  core/storage/gcp.go
  core/storage/local.go
  core/storage/minio.go
  core/storage/mpath/path.go
  core/storage/mpath/path_test.go
  core/storage/tencent.go
  go.mod
  go.sum
  internal/log/log.go
  internal/progressbar/progressbar.go
Labels: ci-passed, dco-passed, lgtm, approved, size/XXL

#694 storage: improve copy retry logic
  core/storage/client.go
  core/storage/copy_task.go
Labels: ci-passed, dco-passed, lgtm, approved, size/S

#698 migrate, storage: re apply stage cred when expire
  cmd/migrate/migrate.go
  core/migrate/task.go
  core/storage/aliyun.go
  core/storage/azure.go
  core/storage/client.go
  core/storage/copy_task_test.go
  core/storage/factory.go
  core/storage/factory_test.go
  core/storage/gcp.go
  core/storage/gcp_native.go
  core/storage/minio.go
  core/storage/tencent.go
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/L

#699 milvus: retry GetPersistentSegmentInfo when return error
  core/client/milvus/grpc.go
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/S

#706 restore: fix typo
  core/restore/task.go
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XS

#707 test: add property check after restore
  tests/testcases/test_restore_backup.py
Labels: dco-passed, lgtm, approved, kind/improvement, size/M

#712 test: add more case for useV2Restore param
  tests/testcases/test_restore_backup.py
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XS
