Repository zilliztech/milvus-backup, pull requests merged in 2025-03, with the labels that each got.

#559 restore: fix bug where chunked segment was processed but not used
  core/client/restful.go
  core/restore/collection.go
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XS

#565 ci: refine get_latest_tag.py script
  scripts/get_latest_tag.py
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/XS

#567 restore: truncate binlog by timestamp only when specified
  core/backup_impl_restore_backup.go
  core/proto/backup.proto
  core/proto/backuppb/backup.pb.go
  core/restore/collection.go
  core/restore/collection_test.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/L

#569 client: add aimd limit for create
  core/client/grpc.go
Labels: ci-passed, dco-passed, approved, kind/improvement, size/M

#572 ci: update dependabot.yml to include Go and Python dependencies and fix some cve
  .github/dependabot.yml
  tests/requirements.txt
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/M

#573 restore: restore only meta if meta-only flag is set
  core/restore/collection.go
Labels: ci-passed, dco-passed, lgtm, approved, size/S

#575 core, client: improve log readability during the flush process
  core/backup_impl_create_backup.go
  core/client/grpc.go
Labels: ci-passed, dco-passed, lgtm, approved, size/M

#576 test: add text embedding function test
  .github/dependabot.yml
  .github/workflows/main.yaml
  .github/workflows/nightly.yaml
  deployment/standalone/docker-compose-tei.yml
  scripts/check_healthy.sh
  tests/check_embedding_service.py
  tests/conftest.py
  tests/requirements.txt
  tests/testcases/test_restore_backup.py
  tests/utils/util_pymilvus.py
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/L

#580 restore: fix dropCollection flag not work
  .mockery.yaml
  Makefile
  core/backup_impl_restore_backup.go
  core/mocks/grpc_mock.go
  core/proto/backuppb/backup.pb.go
  core/restore/collection.go
  core/restore/collection_test.go
  core/restore/task.go
  core/restore/task_test.go
  go.mod
Labels: dco-passed, lgtm, approved, size/XXL

#602 ci: update mergify config and remove dependabot config
  .github/dependabot.yml
  .github/mergify.yml
Labels: dco-passed, lgtm, approved, kind/improvement, size/M

#604 test: Add test cases for json path index backup
  tests/base/client_base.py
  tests/common/common_func.py
  tests/common/common_type.py
  tests/testcases/test_restore_backup.py
  tests/utils/util_pymilvus.py
Labels: ci-passed, dco-passed, lgtm, approved, size/L

#607 ci: fix nightly for text embedding function test
  .github/workflows/nightly.yaml
Labels: ci-passed, dco-passed, lgtm, approved, kind/improvement, size/M
